version: '3'
services:
  web:
    image: nginx
    container_name: web
    volumes:
    - ./web/app.conf:/etc/nginx/conf.d/default.conf
    environment:
      XDEBUG_OUTPUT_DIR: "/tmp/xdebug"
    ports:
    - "8080:80"
    depends_on:
    - app


  app:
    build:
      context: app
    container_name: app
    environment:
      - PHP_IDE_CONFIG=serverName=myserver
    volumes:
    - ./public:/var/www/public
    - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini