version: '3'
services:
  web:
    image: nginx
    volumes:
    - ./web/api.conf:/etc/nginx/conf.d/default.conf
    environment:
      XDEBUG_OUTPUT_DIR: "/tmp/xdebug"
    ports:
    - "8080:80"
    depends_on:
    - api


  api:
    build:
      context: ./api
    environment:
      - PHP_IDE_CONFIG=serverName=ololo
    volumes:
    - ./public:/var/www/public
    - ./api/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini